// AI news curated on fivenodes.ai/news
export const NEWS_ITEMS = [
  ["The emergence of the web data infrastructure layer for AI", "MIT Tech Review", "Jun 24, 2026", "Enterprises require scalable data infrastructure to leverage AI's potential while addressing challenges with unstructured information."],
  ["The $400 million machine powering the future of chipmaking", "MIT Tech Review", "Jun 23, 2026", "A new $400 million chipmaking machine is crucial for future semiconductor production."],
  ["Three things to watch amid Anthropic's latest feud with the government", "MIT Tech Review", "Jun 22, 2026", "Anthropic faces conflict with the US government regarding AI initiatives and regulatory challenges."],
  ["The Atlantic created a searchable database of the music used to train AI", "The Verge AI", "Jun 20, 2026", "A searchable database provides access to four music datasets used for training AI."],
  ["The film about Sam Altman has been dropped by Amazon MGM", "The Verge AI", "Jun 19, 2026", "Amazon MGM dropped the film 'Artificial' focusing on OpenAI's CEO and his five-day departure in 2023."],
  ["Barret Zoph is out at OpenAI again after just five months", "The Verge AI", "Jun 19, 2026", "An executive departed OpenAI after a brief tenure as head of enterprise AI sales."],
  ["Who decides when AI is too dangerous?", "The Verge AI", "Jun 18, 2026", "Recent discussions examine complexities of determining when AI technologies become too dangerous."],
  ["Photoshop and Premiere now have AI assistants", "The Verge AI", "Jun 18, 2026", "Adobe launched AI assistants in its Creative Cloud suite, enhancing user experience."],
  ["Adobe's redesigned AI studio remembers what your creations look like", "The Verge AI", "Jun 18, 2026", "Adobe's Firefly assistant was redesigned to offer persistent context and reusable assets."],
  ["Midjourney goes from generating cat images to full-body ultrasound scans", "The Verge AI", "Jun 18, 2026", "Midjourney introduced The Midjourney Scanner, its first hardware product."],
  ["Can anyone look cool wearing Snap's $2,000 glasses?", "The Verge AI", "Jun 17, 2026", "Snap launched $2,195 Specs glasses integrating computing into everyday life."],
  ["Two-thirds of Americans think AI is advancing too quickly", "The Verge AI", "Jun 17, 2026", "A Pew Research poll shows 63% believe AI technology is advancing too quickly."],
  ["Google's first smart speaker in six years arrives next week", "The Verge AI", "Jun 17, 2026", "Google is releasing its first new smart speaker in six years with preorders available."],
  ["The next humanoid robot might not look human at all", "The Verge AI", "Jun 17, 2026", "Genesis AI introduces a humanoid robot focusing on functionality over human appearance."],
  ["AI search grounded in Facebook posts? What could go wrong?", "The Verge AI", "Jun 16, 2026", "Meta's AI Mode in search struggles with accuracy despite targeting weekend activity suggestions."],
  ["Apple 2027 rumors: AirPods with cameras for AI and the second folding iPhone", "The Verge AI", "Jun 16, 2026", "Apple may release camera-equipped AirPods for AI and a second folding iPhone in late 2027."],
  ["Qualcomm's latest chip hints that more powerful smart glasses could be on the way", "The Verge AI", "Jun 16, 2026", "Qualcomm unveiled the Snapdragon Reality Elite chip to enhance smart glasses capabilities."],
  ["SpaceX is officially buying Cursor for $60 billion", "The Verge AI", "Jun 16, 2026", "SpaceX is acquiring Cursor for $60 billion to enhance AI and social media capabilities."],
  ["Inside the fight over Claude Mythos 5", "The Verge AI", "Jun 16, 2026", "Anthropic faces challenges with the Trump administration regarding release of its latest AI model."],
  ["Facebook's new AI Mode search gets its info from public posts", "The Verge AI", "Jun 15, 2026", "Meta introduced AI Mode for search on Facebook utilizing public posts for results."],
  ["Trump's Anthropic shutdown just made the case for non-American AI", "The Verge AI", "Jun 15, 2026", "Anthropic took AI models offline at White House request, raising concerns about American AI future."],
  ["Amazon security research reportedly led to the White House's Anthropic Fable ban", "The Verge AI", "Jun 13, 2026", "Amazon's cybersecurity research reportedly influenced the White House's ban on Anthropic models."],
  ["Anthropic cuts off Fable 5 and Mythos 5 access following government order", "The Verge AI", "Jun 13, 2026", "Anthropic was ordered to block access to its AI models for national security reasons."],
  ["Apple's new AI photo editing tools mostly work, for better and worse", "The Verge AI", "Jun 12, 2026", "Apple introduced AI photo editing tools in iOS 27, though lagging behind competitors."],
  ["Siri is good now??", "The Verge AI", "Jun 12, 2026", "Apple's updated Siri demonstrates significant functionality improvements over previous versions."],
  ["Elon Musk is the world's first trillionaire", "The Verge AI", "Jun 12, 2026", "Musk became the world's first trillionaire following SpaceX's IPO."],
  ["SpaceX's massive IPO: all the latest news", "The Verge AI", "Jun 12, 2026", "SpaceX's IPO enables public investment in its combined rocket, AI, and social media ventures."],
  ["Jeff Bezos' AI startup aims to build an 'artificial general engineer'", "The Verge AI", "Jun 12, 2026", "Bezos' startup Prometheus aims to create an artificial general engineer for design tools."],
  ["xAI fired an engineer who raised alarms about Grok safety, new lawsuit claims", "TechCrunch AI", "Jun 10, 2026", "A former xAI engineer is suing over alleged wrongful termination related to AI safety concerns."],
  ["Fresh off bond sale, Amazon borrows $17.5B from banks as AI spending continues", "TechCrunch AI", "Jun 10, 2026", "Amazon borrowed $17.5 billion to support ongoing AI investments amid rising debt."],
  ["'AI-pilled' firms spend $7,500 per employee each month on AI", "TechCrunch AI", "Jun 10, 2026", "Companies heavily invested in AI spend approximately $7,500 monthly per employee."],
  ["How an Agent Built a 3D Paris Gallery by Chaining Two Hugging Face Spaces", "Hugging Face Blog", "Jun 9, 2026", "An AI agent successfully created a 3D gallery of Paris by integrating Hugging Face Spaces."],
  ["What Codex unlocks for Notion", "OpenAI Blog", "Jun 9, 2026", "Notion uses Codex for specifications, AI Voice Input for web, and team productivity enhancement."],
  ["Are AI chatbots making us lose control of our brains?", "MIT Tech Review", "Jun 5, 2026", "SXSW London discussions examined AI chatbots' impact on human cognition."],
  ["The Meta hack shows there's more to AI security than Mythos", "MIT Tech Review", "Jun 5, 2026", "Attackers exploited Meta's AI customer support agent for unauthorized Instagram access."],
  ["China has approved the world's first invasive brain-computer chip—here's what's next", "MIT Tech Review", "Jun 1, 2026", "China approved the world's first invasive brain-computer chip for assisting individuals with disabilities."],
  ["OpenAI gives GPT-5.5 Instant a readability upgrade while phasing out two older models", "The Decoder", "May 29, 2026", "OpenAI enhanced GPT-5.5 Instant for natural interactions, discontinuing older models."],
  ["Google fixes several bugs in Gemini usage limits that burned through quotas too fast", "The Decoder", "May 29, 2026", "Google resolved Gemini app bugs causing excessive video quota usage for Ultra members."],
  ["One company reportedly spent $500 million on Claude in one month after failing to cap AI usage", "The Decoder", "May 29, 2026", "A company spent $500 million on Claude licenses monthly due to lack of usage limits."],
  ["OpenAI is giving away its life sciences AI model to help governments prepare for the next pandemic", "The Decoder", "May 29, 2026", "OpenAI provided GPT-Rosalind for free to assist government pandemic preparedness."],
  ["Fed up with vibe coders, dev sneaks data-nuking prompt injection into their code", "Ars Technica", "May 28, 2026", "A developer introduced prompt injection techniques to counteract aesthetics-focused coding."],
  ["YouTube is putting AI labels where you'll actually see them", "The Verge AI", "May 27, 2026", "YouTube enhanced AI labeling by relocating disclosures to more visible video areas."],
  ["Alibaba's latest AI model ran autonomously for 35 hours to optimize code for its own custom chip", "The Decoder", "May 23, 2026", "Alibaba's Qwen3.7-Max autonomously optimized code for a custom chip over 35 hours."],
  ["Anthropic warns Claude Mythos Preview finds bugs faster than developers can patch them", "The Decoder", "May 23, 2026", "Claude Mythos Preview identified over 10,000 critical vulnerabilities faster than developers can address."],
  ["The Gulf's AI Boom Has an Undersea Cable Problem", "Wired AI", "May 22, 2026", "AI growth in the Gulf region prompts reevaluation of internet infrastructure vulnerabilities."],
  ["Can OpenAI's 'Master of Disaster' Fix AI's Reputation Crisis?", "Wired AI", "May 22, 2026", "OpenAI's global affairs chief works to mitigate AI concerns while advocating supportive legislation."],
  ["AI video is moving beyond clip slop", "The Verge AI", "May 21, 2026", "AI video technology shifts from basic content creation to sophisticated productions."],
  ["Spotify is launching AI-generated remixes", "The Verge AI", "May 21, 2026", "Spotify partnered with Universal Music Group for user-created AI remixes and covers."],
  ["Jensen Huang says he's found a 'brand new' $200B market for Nvidia", "TechCrunch AI", "May 21, 2026", "Nvidia's CEO predicts a new $200 billion market for AI agent-focused CPUs."],
  ["AI search startups are blowing up", "TechCrunch AI", "May 20, 2026", "AI search has become highly attractive, with numerous consumer-focused startups emerging."],
];
